"""initial: hot_topics, topics, contents, agent_tasks

Revision ID: 490281ae397a
Revises: 
Create Date: 2026-06-10 16:26:13.002889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '490281ae397a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('workflow_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_node', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('session_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('share_expires_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_index('idx_agent_tasks_share', 'agent_tasks', ['share_token'], unique=False)
    op.create_index('idx_agent_tasks_status', 'agent_tasks', ['status', 'deleted_at', 'updated_at'], unique=False)
    op.create_index('idx_agent_tasks_thread', 'agent_tasks', ['thread_id'], unique=False)
    op.create_index('idx_agent_tasks_user', 'agent_tasks', ['user_id', 'deleted_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_agent_tasks_user_id'), 'agent_tasks', ['user_id'], unique=False)
    op.create_table('hot_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('source_platform', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hot_index', sa.Integer(), nullable=False),
    sa.Column('trend', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('audience', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('sentiment', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('agent_task_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['hot_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('style', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('source_hot_topic_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_hot_topic_id'], ['hot_topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('style', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('agent_task_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contents')
    op.drop_table('topics')
    op.drop_table('hot_topics')
    op.drop_index(op.f('ix_agent_tasks_user_id'), table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_user', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_thread', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_status', table_name='agent_tasks')
    op.drop_index('idx_agent_tasks_share', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
